### ISSUE TITLE
phantomjs dependency issue

### ISSUE THREAD

**Issue by daschne8** [learn-co-curriculum/return-string-data-lab#19]
for test 
rspec ./spec/features/product_feature_spec.rb:8 # Product Index gets the description and inventory
gives phantomjs dependency error

**Comment by BMWeygant** [comment]
Same issue I believe, I get something that says "Got 0 failures and 2 other errors". Terminal output below

```learn

ProductsController
  POST create
    creates a new product
  GET inventory
    returns true or false appropriately
  GET description
    returns the description as a plain string

Product Index
Capybara starting Puma...
* Version 3.12.1 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:63118
  gets the description and inventory (FAILED - 1)

Product
  should respond to #description
  should respond to #inventory

invoices_index_view
  renders the invoice partial
  renders the invoice partial using the abstract method of rendering collection
  handles empty collections

invoices_index_view
  renders the invoice partial
  renders the invoice partial using the abstract method of rendering collection
  handles empty collections

Failures:

  1) Product Index gets the description and inventory
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit products_path
          
          Cliver::Dependency::NotFound:
            Could not find an executable ["phantomjs"] on your path.
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:143:in `raise_not_found!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:116:in `detect!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver.rb:24:in `detect!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:53:in `initialize'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `new'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `start'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:47:in `client'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:27:in `browser'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:100:in `visit'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara/session.rb:276:in `visit'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
          # ./spec/features/product_feature_spec.rb:10:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error:
            raise Dependency::NotFound.new(
              "Could not find an executable #{@executables} on your path.")
          
          Cliver::Dependency::NotFound:
            Could not find an executable ["phantomjs"] on your path.
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:143:in `raise_not_found!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver/dependency.rb:116:in `detect!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/cliver-0.3.2/lib/cliver.rb:24:in `detect!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:53:in `initialize'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `new'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/client.rb:16:in `start'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:47:in `client'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:27:in `browser'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/poltergeist-1.18.1/lib/capybara/poltergeist/driver.rb:208:in `reset!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara/session.rb:128:in `reset!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara.rb:321:in `block in reset_sessions!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara.rb:321:in `reverse_each'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara.rb:321:in `reset_sessions!'
          # /Users/PurpleCloudEntertainment/.rvm/gems/ruby-2.6.1/gems/capybara-3.22.0/lib/capybara/rspec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 2.21 seconds (files took 2.41 seconds to load)
12 examples, 1 failure

Failed examples:

rspec ./spec/features/product_feature_spec.rb:8 # Product Index gets the description and inventory```

**Comment by ValerieHMoore** [comment]
Adding gem ‘phantomjs’, :require => ‘phantomjs/poltergeist’ will fix this issue. Delete gemfile.lock first and then bundle install.
